export const SESSION_PROMPT_MAX_LENGTH = 20000;
export const FUSION_PROMPT_MAX_LENGTH = 60000;
export const FUSION_INSTRUCTIONS_MAX_LENGTH = 4000;
export const GOAL_MAX_CONTINUATIONS_MIN = 1;
export const GOAL_MAX_CONTINUATIONS_MAX = 200;
